import React from 'react';
import { NextResponse } from 'next/server';
import { Document, Page, Text, View, StyleSheet, renderToBuffer } from '@react-pdf/renderer';
import { createRouteHandlerClient } from '@/lib/supabase-server';

export const dynamic = 'force-dynamic';

const styles = StyleSheet.create({ page: { padding: 42, fontSize: 11, color: '#172554' }, title: { fontSize: 22, marginBottom: 6, fontWeight: 700 }, subtitle: { color: '#64748b', marginBottom: 24 }, box: { border: '1 solid #e2e8f0', borderRadius: 8, padding: 14, marginBottom: 16 }, row: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 7, borderBottom: '1 solid #f1f5f9' }, label: { color: '#64748b' }, total: { fontSize: 16, fontWeight: 700, marginTop: 8 }, line: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 5 }, footer: { marginTop: 28, color: '#94a3b8', fontSize: 9 } });

function money(value) { return `NGN ${Number(value || 0).toLocaleString('en-NG', { minimumFractionDigits: 2 })}`; }
function PayslipDocument({ school, staff, run, payslip }) {
  return <Document><Page size="A4" style={styles.page}><Text style={styles.title}>{school.name}</Text><Text style={styles.subtitle}>Staff payslip · {new Date(run.month).toLocaleDateString('en-NG', { month: 'long', year: 'numeric' })}</Text><View style={styles.box}><View style={styles.row}><Text style={styles.label}>Staff member</Text><Text>{staff.full_name}</Text></View><View style={styles.row}><Text style={styles.label}>Email</Text><Text>{staff.email || '—'}</Text></View><View style={styles.row}><Text style={styles.label}>Payroll status</Text><Text>{run.status}</Text></View></View><View style={styles.box}><View style={styles.line}><Text>Basic salary</Text><Text>{money(payslip.basic_salary)}</Text></View><View style={styles.line}><Text>Total allowances</Text><Text>{money(payslip.total_allowances)}</Text></View><View style={styles.line}><Text>Total deductions</Text><Text>- {money(payslip.total_deductions)}</Text></View><Text style={styles.total}>Net pay: {money(payslip.net_pay)}</Text></View><Text style={styles.footer}>Generated by SBA School Module. Finalized payslips are immutable payroll history.</Text></Page></Document>;
}

export async function GET(request, { params }) {
  const supabase = createRouteHandlerClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return NextResponse.json({ error: 'Not signed in.' }, { status: 401 });
  const { data: payslip } = await supabase.from('payslips').select('id, payroll_run_id, staff_id, basic_salary, total_allowances, total_deductions, net_pay').eq('id', params.id).maybeSingle();
  if (!payslip) return NextResponse.json({ error: 'Payslip not found or not accessible.' }, { status: 404 });
  const [{ data: run }, { data: staff }, { data: profile }] = await Promise.all([
    supabase.from('payroll_runs').select('id, school_id, month, status').eq('id', payslip.payroll_run_id).single(),
    supabase.from('profiles').select('id, full_name, email, role, school_id').eq('id', payslip.staff_id).single(),
    supabase.from('profiles').select('id, role, school_id').eq('id', user.id).single(),
  ]);
  if (!run || !staff || !profile) return NextResponse.json({ error: 'Payslip context not found.' }, { status: 404 });
  const canRead = payslip.staff_id === user.id || (profile.role === 'admin' || (profile.role === 'principal' && profile.school_id === run.school_id));
  if (!canRead) return NextResponse.json({ error: 'You can only download your own payslip.' }, { status: 403 });
  const { data: school } = await supabase.from('schools').select('name').eq('id', run.school_id).single();
  const buffer = await renderToBuffer(<PayslipDocument school={school || { name: 'SBA School' }} staff={staff} run={run} payslip={payslip} />);
  return new NextResponse(buffer, { status: 200, headers: { 'Content-Type': 'application/pdf', 'Content-Disposition': `attachment; filename="payslip-${run.month}-${payslip.staff_id}.pdf"` } });
}
