'use client';

// components/CountdownLoopRecorder.js
//
// Renders one countdown_loop content_assets row (a "3 things costing you
// marks in X" script generated by /api/admin/countdown-loops/generate)
// into a short countdown-reveal 9:16 video: title card, then rank #3, #2,
// #1 each drop in turn (with a small "completed ranks" ladder building up
// at the top so the viewer can see the countdown progressing), then a CTA
// card lands on #1. Same canvas + Web Audio API + MediaRecorder technique
// as QuoteLoopRecorder.js and PastQuestionLoopRecorder.js — this file only
// differs in its draw() timeline; the background/audio/recording plumbing
// below is intentionally a near-identical copy of
// PastQuestionLoopRecorder.js rather than a shared abstraction, matching
// how each loop recorder in this codebase is self-contained.

import { useRef, useState, useEffect, useCallback } from 'react';
import { createBrowserClient } from '@/lib/supabase';

const CANVAS_W = 1080;
const CANVAS_H = 1920; // 9:16 — TikTok / IG Reels / YouTube Shorts
const BRAND_BLUE = '#1a73e8';
const BRAND_YELLOW = '#FFCC00';
const GREEN = '#22c55e';
const DARK = '#0f172a';
const BUCKET = 'countdown-loops'; // create this bucket in Supabase storage (public read, authenticated upload) — same policy shape as quote-loops/past-question-loops — before first use

function wrapText(ctx, text, maxWidth) {
  const words = String(text || '').split(' ');
  const lines = [];
  let current = '';
  for (const word of words) {
    const test = current ? `${current} ${word}` : word;
    if (ctx.measureText(test).width > maxWidth && current) {
      lines.push(current);
      current = word;
    } else {
      current = test;
    }
  }
  if (current) lines.push(current);
  return lines;
}

function pickMimeType() {
  const candidates = [
    'video/mp4;codecs=avc1.42E01E,mp4a.40.2',
    'video/mp4;codecs=avc1,mp4a.40.2',
    'video/mp4',
    'video/webm;codecs=vp9,opus',
    'video/webm;codecs=vp8,opus',
    'video/webm',
  ];
  for (const type of candidates) {
    if (typeof MediaRecorder !== 'undefined' && MediaRecorder.isTypeSupported(type)) return type;
  }
  return '';
}

function extensionForMimeType(mimeType) {
  return (mimeType || '').includes('mp4') ? 'mp4' : 'webm';
}

// ── Reveal timeline, in ms from recording start ──
// Title card, then rank 3 and 2 get equal time, rank 1 gets extra weight
// (it's the payoff the countdown format is built to earn), then a CTA card.
const TITLE_END_MS = 1300;
const ITEM3_START_MS = TITLE_END_MS;
const ITEM3_DURATION_MS = 2100;
const ITEM2_START_MS = ITEM3_START_MS + ITEM3_DURATION_MS;
const ITEM2_DURATION_MS = 2100;
const ITEM1_START_MS = ITEM2_START_MS + ITEM2_DURATION_MS;
const ITEM1_DURATION_MS = 2800; // #1 gets the extra beat — it's the reveal the viewer stayed for
const CTA_START_MS = ITEM1_START_MS + ITEM1_DURATION_MS;
const CTA_DURATION_MS = 1900;
const RECORD_SECONDS = Math.ceil((CTA_START_MS + CTA_DURATION_MS) / 1000); // ~10s

const ITEM_TIMELINE = [
  { rank: 3, start: ITEM3_START_MS, end: ITEM2_START_MS },
  { rank: 2, start: ITEM2_START_MS, end: ITEM1_START_MS },
  { rank: 1, start: ITEM1_START_MS, end: CTA_START_MS },
];

/**
 * @param {Object} props
 * @param {Object} props.contentAsset - a content_assets row (id, title, body = countdown title, metadata.{items,cta,background})
 * @param {(videoUrl: string) => void} [props.onSaved]
 */
export default function CountdownLoopRecorder({ contentAsset, onSaved }) {
  const canvasRef = useRef(null);
  const bgVideoRef = useRef(null);
  const bgImageRef = useRef(null);
  const audioRef = useRef(null);
  const audioCtxRef = useRef(null);
  const rafRef = useRef(null);
  const recorderRef = useRef(null);
  const chunksRef = useRef([]);
  const startTimeRef = useRef(0);
  const stopTimerRef = useRef(null);

  const [status, setStatus] = useState('idle'); // idle | recording | finished | uploading | saved | error
  const [videoBlobUrl, setVideoBlobUrl] = useState(null);
  const [videoBlob, setVideoBlob] = useState(null);
  const [errorMsg, setErrorMsg] = useState(null);
  const [tracks, setTracks] = useState([]);
  const [bgReady, setBgReady] = useState(false);

  const background = contentAsset.metadata?.background || null;
  const title = contentAsset.body || '';
  const items = contentAsset.metadata?.items || []; // [{rank, point, detail}], ordered 3,2,1
  const cta = contentAsset.metadata?.cta || null;

  const itemByRank = (rank) => items.find((it) => it.rank === rank);

  // ── Discover music tracks + preload background on mount ────────────────
  // Reuses the quote-loops music library, same as PastQuestionLoopRecorder.
  useEffect(() => {
    fetch('/api/admin/quote-loops/audio-list')
      .then((r) => r.json())
      .then((d) => setTracks(d.tracks || []))
      .catch(() => setTracks([]));

    if (background?.type === 'photo') {
      const img = new Image();
      img.crossOrigin = 'anonymous';
      img.onload = () => setBgReady(true);
      img.onerror = () => setBgReady(true);
      img.src = background.url;
      bgImageRef.current = img;
    } else if (background?.type === 'video') {
      const vid = bgVideoRef.current;
      if (vid) {
        vid.src = background.url;
        vid.crossOrigin = 'anonymous';
        vid.muted = true;
        vid.loop = true;
        vid.oncanplaythrough = () => setBgReady(true);
        vid.onerror = () => setBgReady(true);
        vid.load();
      }
    } else {
      setBgReady(true);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // ── Drawing ─────────────────────────────────────────────────────────────
  const draw = useCallback(
    (elapsedMs) => {
      const canvas = canvasRef.current;
      if (!canvas) return;
      const ctx = canvas.getContext('2d');
      const W = CANVAS_W, H = CANVAS_H;
      const t = Math.min(1, elapsedMs / (RECORD_SECONDS * 1000));

      // ── Background layer (identical technique to the other loop recorders) ──
      if (background?.type === 'video' && bgVideoRef.current?.readyState >= 2) {
        const vid = bgVideoRef.current;
        const scale = Math.max(W / vid.videoWidth, H / vid.videoHeight);
        const dw = vid.videoWidth * scale, dh = vid.videoHeight * scale;
        ctx.drawImage(vid, (W - dw) / 2, (H - dh) / 2, dw, dh);
        ctx.fillStyle = 'rgba(15,23,42,0.6)';
        ctx.fillRect(0, 0, W, H);
      } else if (background?.type === 'photo' && bgImageRef.current?.complete && bgImageRef.current.naturalWidth) {
        const img = bgImageRef.current;
        const zoom = 1 + 0.08 * t;
        const scale = Math.max(W / img.naturalWidth, H / img.naturalHeight) * zoom;
        const dw = img.naturalWidth * scale, dh = img.naturalHeight * scale;
        ctx.drawImage(img, (W - dw) / 2, (H - dh) / 2, dw, dh);
        ctx.fillStyle = 'rgba(15,23,42,0.6)';
        ctx.fillRect(0, 0, W, H);
      } else {
        const angle = t * Math.PI * 0.4;
        const gradient = ctx.createLinearGradient(
          W / 2 + Math.cos(angle) * W, H / 2 + Math.sin(angle) * H,
          W / 2 - Math.cos(angle) * W, H / 2 - Math.sin(angle) * H
        );
        gradient.addColorStop(0, DARK);
        gradient.addColorStop(1, BRAND_BLUE);
        ctx.fillStyle = gradient;
        ctx.fillRect(0, 0, W, H);
      }

      ctx.textAlign = 'center';
      ctx.textBaseline = 'alphabetic';

      // ── Ladder — small chip per rank at the top, builds up as ranks pass ──
      // Shown from the moment item 3 starts through the end of the video, so
      // the viewer always sees how many are left / already revealed.
      if (elapsedMs >= ITEM3_START_MS) {
        const chipY = 140;
        const chipGap = 130;
        const startX = W / 2 - chipGap;
        [3, 2, 1].forEach((rank, i) => {
          const entry = ITEM_TIMELINE.find((e) => e.rank === rank);
          const isDone = elapsedMs >= entry.end;
          const isActive = elapsedMs >= entry.start && elapsedMs < entry.end;
          const cx = startX + i * chipGap;
          ctx.beginPath();
          ctx.arc(cx, chipY, isActive ? 34 : 28, 0, Math.PI * 2);
          ctx.fillStyle = isDone ? GREEN : isActive ? BRAND_YELLOW : 'rgba(255,255,255,0.15)';
          ctx.fill();
          ctx.font = isActive ? '800 32px Arial' : '700 26px Arial';
          ctx.fillStyle = isDone || isActive ? '#0f172a' : 'rgba(255,255,255,0.6)';
          ctx.fillText(String(rank), cx, chipY + (isActive ? 11 : 9));
        });
      }

      // ── Title card (fades out once item 3 starts) ──
      if (elapsedMs < ITEM3_START_MS) {
        const introT = Math.min(1, elapsedMs / 500);
        const eased = 1 - Math.pow(1 - introT, 3);
        const outT = elapsedMs > TITLE_END_MS - 300 ? Math.min(1, (elapsedMs - (TITLE_END_MS - 300)) / 300) : 0;

        ctx.save();
        ctx.globalAlpha = eased * (1 - outT);
        ctx.font = 'bold 28px Arial';
        ctx.fillStyle = BRAND_YELLOW;
        ctx.fillText('COUNTDOWN', W / 2, H / 2 - 160);

        ctx.font = '800 56px Arial';
        ctx.fillStyle = '#ffffff';
        ctx.shadowColor = 'rgba(0,0,0,0.6)';
        ctx.shadowBlur = 12;
        const titleLines = wrapText(ctx, title, W - 140).slice(0, 4);
        titleLines.forEach((line, i) => ctx.fillText(line, W / 2, H / 2 - 40 + i * 66));
        ctx.restore();
      }

      // ── Active item (big rank number, point, detail) ──
      const activeEntry = ITEM_TIMELINE.find((e) => elapsedMs >= e.start && elapsedMs < e.end);
      if (activeEntry) {
        const item = itemByRank(activeEntry.rank);
        if (item) {
          const localT = Math.min(1, (elapsedMs - activeEntry.start) / 350);
          const eased = 1 - Math.pow(1 - localT, 3);
          const slideY = (1 - eased) * 30;

          ctx.save();
          ctx.globalAlpha = eased;

          // Giant rank number
          ctx.font = '900 220px Arial';
          ctx.fillStyle = activeEntry.rank === 1 ? BRAND_YELLOW : 'rgba(255,255,255,0.92)';
          ctx.shadowColor = 'rgba(0,0,0,0.5)';
          ctx.shadowBlur = 16;
          ctx.fillText(String(activeEntry.rank), W / 2, 620 + slideY);

          // Point (short punchy label)
          ctx.shadowBlur = 8;
          ctx.font = '800 46px Arial';
          ctx.fillStyle = '#ffffff';
          const pointLines = wrapText(ctx, item.point, W - 140).slice(0, 3);
          pointLines.forEach((line, i) => ctx.fillText(line, W / 2, 760 + i * 56 + slideY));

          // Detail panel
          const detailTop = 760 + pointLines.length * 56 + 60 + slideY;
          ctx.font = '500 32px Arial';
          const detailLines = wrapText(ctx, item.detail, W - 200).slice(0, 6);
          const detailLineH = 42;
          const panelH = detailLines.length * detailLineH + 70;

          ctx.shadowBlur = 0;
          ctx.fillStyle = 'rgba(15,23,42,0.75)';
          ctx.beginPath();
          if (ctx.roundRect) ctx.roundRect(70, detailTop, W - 140, panelH, 20); else ctx.rect(70, detailTop, W - 140, panelH);
          ctx.fill();
          ctx.strokeStyle = activeEntry.rank === 1 ? BRAND_YELLOW : 'rgba(255,255,255,0.35)';
          ctx.lineWidth = activeEntry.rank === 1 ? 3 : 2;
          ctx.stroke();

          ctx.textAlign = 'left';
          ctx.font = '500 30px Arial';
          ctx.fillStyle = 'rgba(255,255,255,0.95)';
          detailLines.forEach((line, i) => ctx.fillText(line, 100, detailTop + 48 + i * detailLineH));
          ctx.restore();
        }
      }

      // ── CTA card ──
      if (elapsedMs >= CTA_START_MS && cta) {
        const localT = Math.min(1, (elapsedMs - CTA_START_MS) / 400);
        const eased = 1 - Math.pow(1 - localT, 3);

        ctx.save();
        ctx.globalAlpha = eased;
        ctx.textAlign = 'center';
        ctx.font = '800 30px Arial';
        ctx.fillStyle = GREEN;
        ctx.fillText('✓ THAT\'S THE ONE TO FIX', W / 2, H / 2 + 40);

        ctx.font = '700 42px Arial';
        ctx.fillStyle = '#ffffff';
        ctx.shadowColor = 'rgba(0,0,0,0.6)';
        ctx.shadowBlur = 10;
        const ctaLines = wrapText(ctx, cta, W - 160).slice(0, 4);
        ctaLines.forEach((line, i) => ctx.fillText(line, W / 2, H / 2 + 110 + i * 54));
        ctx.restore();
      }

      // Brand mark
      ctx.textAlign = 'left';
      ctx.font = 'bold 26px Arial';
      ctx.fillStyle = BRAND_YELLOW;
      ctx.fillText('SHINEY BRAIN ACADEMY', 50, H - 50);
    },
    [background, title, items, cta]
  );

  useEffect(() => {
    function loop() {
      const elapsed = status === 'recording' ? performance.now() - startTimeRef.current : 0;
      draw(elapsed);
      rafRef.current = requestAnimationFrame(loop);
    }
    if (status === 'recording') {
      rafRef.current = requestAnimationFrame(loop);
    } else {
      draw(CTA_START_MS + 800); // static idle frame — CTA card visible, all ranks shown as done
    }
    return () => {
      if (rafRef.current) cancelAnimationFrame(rafRef.current);
    };
  }, [status, draw]);

  // ── Start / stop ─────────────────────────────────────────────────────
  const startRecording = async () => {
    setErrorMsg(null);
    setVideoBlobUrl(null);
    setVideoBlob(null);

    try {
      const AudioContextCls = window.AudioContext || window.webkitAudioContext;
      const audioCtx = new AudioContextCls();
      audioCtxRef.current = audioCtx;

      const dest = audioCtx.createMediaStreamDestination();

      if (tracks.length > 0 && audioRef.current) {
        const track = tracks[Math.floor(Math.random() * tracks.length)];
        audioRef.current.src = track;
        audioRef.current.loop = true;
        audioRef.current.currentTime = 0;
        await audioRef.current.play().catch(() => {});
        const source = audioCtx.createMediaElementSource(audioRef.current);
        source.connect(dest);
        source.connect(audioCtx.destination);
      }

      if (background?.type === 'video' && bgVideoRef.current) {
        bgVideoRef.current.currentTime = 0;
        bgVideoRef.current.play().catch(() => {});
      }

      const canvasStream = canvasRef.current.captureStream(30);
      const combined = new MediaStream([
        ...canvasStream.getVideoTracks(),
        ...dest.stream.getAudioTracks(),
      ]);

      const recorderOptions = { videoBitsPerSecond: 550_000, audioBitsPerSecond: 64_000 };
      const mimeType = pickMimeType();
      if (mimeType) recorderOptions.mimeType = mimeType;

      const recorder = new MediaRecorder(combined, recorderOptions);
      chunksRef.current = [];
      recorder.ondataavailable = (e) => {
        if (e.data.size > 0) chunksRef.current.push(e.data);
      };
      recorder.onstop = () => {
        const blob = new Blob(chunksRef.current, { type: mimeType || 'video/webm' });
        setVideoBlob(blob);
        setVideoBlobUrl(URL.createObjectURL(blob));
        setStatus('finished');
      };
      recorderRef.current = recorder;

      startTimeRef.current = performance.now();
      recorder.start();
      setStatus('recording');

      stopTimerRef.current = setTimeout(finishRecording, RECORD_SECONDS * 1000);
    } catch (err) {
      setStatus('error');
      setErrorMsg(`Could not start recording: ${err.message}`);
    }
  };

  function finishRecording() {
    if (stopTimerRef.current) clearTimeout(stopTimerRef.current);
    if (recorderRef.current && recorderRef.current.state !== 'inactive') recorderRef.current.stop();
    if (audioRef.current) audioRef.current.pause();
    if (bgVideoRef.current) bgVideoRef.current.pause();
    if (audioCtxRef.current) audioCtxRef.current.close().catch(() => {});
  }

  const cancelRecording = () => {
    if (stopTimerRef.current) clearTimeout(stopTimerRef.current);
    if (recorderRef.current) recorderRef.current.onstop = null;
    if (recorderRef.current && recorderRef.current.state !== 'inactive') recorderRef.current.stop();
    if (audioRef.current) audioRef.current.pause();
    if (bgVideoRef.current) bgVideoRef.current.pause();
    if (audioCtxRef.current) audioCtxRef.current.close().catch(() => {});
    setStatus('idle');
  };

  // ── Save: upload blob to storage, then tell the server to record it ──
  const saveToContentAsset = async () => {
    if (!videoBlob) return;
    setStatus('uploading');
    setErrorMsg(null);
    try {
      const supabase = createBrowserClient();
      const ext = extensionForMimeType(videoBlob.type);
      const path = `${contentAsset.id}/${Date.now()}.${ext}`;

      const { error: uploadError } = await supabase.storage
        .from(BUCKET)
        .upload(path, videoBlob, { contentType: videoBlob.type || 'video/webm', upsert: true });
      if (uploadError) throw uploadError;

      const { data: urlData } = supabase.storage.from(BUCKET).getPublicUrl(path);

      const res = await fetch('/api/admin/countdown-loops/save', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          contentAssetId: contentAsset.id,
          videoUrl: urlData.publicUrl,
          durationSeconds: RECORD_SECONDS,
        }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error || 'Save failed');

      setStatus('saved');
      onSaved?.(urlData.publicUrl);
    } catch (err) {
      setStatus('finished');
      setErrorMsg(err.message);
    }
  };

  return (
    <div className="space-y-4">
      <canvas
        ref={canvasRef}
        width={CANVAS_W}
        height={CANVAS_H}
        className="w-full max-w-[280px] aspect-[9/16] mx-auto rounded-2xl border shadow-sm bg-black"
      />
      <video ref={bgVideoRef} muted playsInline className="hidden" />
      <audio ref={audioRef} crossOrigin="anonymous" className="hidden" />

      <p className="text-xs text-gray-500 text-center">
        {background?.type === 'video' && `Real footage background (${background.source}).`}
        {background?.type === 'photo' && `Photo background with zoom (${background.source}).`}
        {!background && 'No background candidate found — recording on an animated brand gradient.'}
        {' '}Records a {RECORD_SECONDS}s countdown{tracks.length === 0 ? ' — no music tracks found, clip will be silent' : ''}.
      </p>

      {errorMsg && <p className="text-sm text-red-600 text-center">⚠️ {errorMsg}</p>}
      {!bgReady && status === 'idle' && (
        <p className="text-xs text-gray-400 text-center">Loading background…</p>
      )}

      <div className="flex justify-center gap-2">
        {status === 'idle' && (
          <button
            onClick={startRecording}
            disabled={!bgReady}
            className="bg-brand-blue text-white px-5 py-2.5 rounded-xl text-sm font-bold hover:opacity-90 disabled:opacity-50"
          >
            🔴 Start Recording
          </button>
        )}
        {status === 'recording' && (
          <button
            onClick={cancelRecording}
            className="bg-red-100 text-red-600 px-5 py-2.5 rounded-xl text-sm font-bold hover:bg-red-200"
          >
            ⏹ Cancel
          </button>
        )}
        {(status === 'finished' || status === 'saved') && videoBlobUrl && (
          <>
            <a
              href={videoBlobUrl}
              download={`${(contentAsset.title || 'countdown-loop').replace(/[^a-z0-9]+/gi, '-').toLowerCase()}.${extensionForMimeType(videoBlob?.type)}`}
              className="bg-gray-100 text-gray-700 px-5 py-2.5 rounded-xl text-sm font-bold hover:bg-gray-200"
            >
              ⬇ Download
            </a>
            {status === 'finished' ? (
              <button
                onClick={saveToContentAsset}
                className="bg-emerald-600 text-white px-5 py-2.5 rounded-xl text-sm font-bold hover:opacity-90"
              >
                💾 Save
              </button>
            ) : (
              <span className="text-sm font-bold text-emerald-600 px-3 py-2.5">✓ Saved</span>
            )}
          </>
        )}
        {status === 'uploading' && (
          <span className="text-sm font-bold text-gray-500 px-3 py-2.5">Uploading…</span>
        )}
      </div>
    </div>
  );
}
