'use client';

// components/PastQuestionLoopRecorder.js
//
// Renders one past_question_loop content_assets row (a JAMB/WAEC/NECO-style
// MCQ generated by /api/admin/past-question-loops/generate) into a short
// quiz-reveal 9:16 video: question + 4 options appear first, then the
// correct option highlights green and a short explanation fades in
// underneath — real stock footage or a photo with a slow Ken Burns zoom (or
// an animated brand gradient if no background was found) behind it all,
// with background music. Entirely in the browser via <canvas> + Web Audio
// API + MediaRecorder — the exact same technique as QuoteLoopRecorder.js
// and AudiogramRecorder.js, just a different draw() timeline. Deliberately
// NOT screen-capture (getDisplayMedia): that needs an OS permission prompt
// every single recording and produces a non-deterministic capture of
// whatever's on screen — canvas.captureStream() renders exactly this
// component's pixels, headless-safe and reproducible.

import { useRef, useState, useEffect, useCallback } from 'react';
import { createBrowserClient } from '@/lib/supabase';

const CANVAS_W = 1080;
const CANVAS_H = 1920; // 9:16 — TikTok / IG Reels / YouTube Shorts
const BRAND_BLUE = '#1a73e8';
const BRAND_YELLOW = '#FFCC00';
const GREEN = '#22c55e';
const DARK = '#0f172a';
const BUCKET = 'past-question-loops'; // create this bucket in Supabase storage (public read, authenticated upload) — same policy shape as quote-loops — before first use
const RECORD_SECONDS = 9; // question + 4 options + reveal + explanation all need to read comfortably

function wrapText(ctx, text, maxWidth) {
  const words = String(text || '').split(' ');
  const lines = [];
  let current = '';
  for (const word of words) {
    const test = current ? `${current} ${word}` : word;
    if (ctx.measureText(test).width > maxWidth && current) {
      lines.push(current);
      current = word;
    } else {
      current = test;
    }
  }
  if (current) lines.push(current);
  return lines;
}

function pickMimeType() {
  const candidates = [
    // Real MP4 muxing (H.264 + AAC) is what Instagram/TikTok's video
    // processing actually wants — WebM sits there "processing" forever on
    // some platforms. Same list/order as QuoteLoopRecorder.js.
    'video/mp4;codecs=avc1.42E01E,mp4a.40.2',
    'video/mp4;codecs=avc1,mp4a.40.2',
    'video/mp4',
    'video/webm;codecs=vp9,opus',
    'video/webm;codecs=vp8,opus',
    'video/webm',
  ];
  for (const type of candidates) {
    if (typeof MediaRecorder !== 'undefined' && MediaRecorder.isTypeSupported(type)) return type;
  }
  return '';
}

function extensionForMimeType(mimeType) {
  return (mimeType || '').includes('mp4') ? 'mp4' : 'webm';
}

// Reveal timeline, in ms from recording start.
const QUESTION_IN_MS = 500; // question text fades/scales in
const OPTIONS_START_MS = 900; // options begin staggering in
const OPTION_STAGGER_MS = 260; // gap between each option's entrance
const REVEAL_AT_MS = 4200; // correct option highlights + explanation begins
const REVEAL_DURATION_MS = 500;

/**
 * @param {Object} props
 * @param {Object} props.contentAsset - a content_assets row (id, title, body = question, metadata.{options,correctOptionId,explanation,background})
 * @param {(videoUrl: string) => void} [props.onSaved]
 */
export default function PastQuestionLoopRecorder({ contentAsset, onSaved }) {
  const canvasRef = useRef(null);
  const bgVideoRef = useRef(null);
  const bgImageRef = useRef(null);
  const audioRef = useRef(null);
  const audioCtxRef = useRef(null);
  const rafRef = useRef(null);
  const recorderRef = useRef(null);
  const chunksRef = useRef([]);
  const startTimeRef = useRef(0);
  const stopTimerRef = useRef(null);

  const [status, setStatus] = useState('idle'); // idle | recording | finished | uploading | saved | error
  const [videoBlobUrl, setVideoBlobUrl] = useState(null);
  const [videoBlob, setVideoBlob] = useState(null);
  const [errorMsg, setErrorMsg] = useState(null);
  const [tracks, setTracks] = useState([]);
  const [bgReady, setBgReady] = useState(false);

  const background = contentAsset.metadata?.background || null;
  const question = contentAsset.body || '';
  const options = contentAsset.metadata?.options || [];
  const correctOptionId = contentAsset.metadata?.correctOptionId || null;
  const explanation = contentAsset.metadata?.explanation || null;

  // ── Discover music tracks + preload background on mount ────────────────
  // Reuses the quote-loops music library rather than duplicating a second
  // copy of the same royalty-cleared tracks under a second folder.
  useEffect(() => {
    fetch('/api/admin/quote-loops/audio-list')
      .then((r) => r.json())
      .then((d) => setTracks(d.tracks || []))
      .catch(() => setTracks([]));

    if (background?.type === 'photo') {
      const img = new Image();
      img.crossOrigin = 'anonymous';
      img.onload = () => setBgReady(true);
      img.onerror = () => setBgReady(true);
      img.src = background.url;
      bgImageRef.current = img;
    } else if (background?.type === 'video') {
      const vid = bgVideoRef.current;
      if (vid) {
        vid.src = background.url;
        vid.crossOrigin = 'anonymous';
        vid.muted = true;
        vid.loop = true;
        vid.oncanplaythrough = () => setBgReady(true);
        vid.onerror = () => setBgReady(true);
        vid.load();
      }
    } else {
      setBgReady(true);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // ── Drawing ─────────────────────────────────────────────────────────────
  const draw = useCallback(
    (elapsedMs) => {
      const canvas = canvasRef.current;
      if (!canvas) return;
      const ctx = canvas.getContext('2d');
      const W = CANVAS_W, H = CANVAS_H;
      const t = Math.min(1, elapsedMs / (RECORD_SECONDS * 1000));
      const revealed = elapsedMs >= REVEAL_AT_MS;
      const revealT = Math.min(1, Math.max(0, (elapsedMs - REVEAL_AT_MS) / REVEAL_DURATION_MS));
      const revealEased = 1 - Math.pow(1 - revealT, 3);

      // ── Background layer (identical technique to QuoteLoopRecorder) ──
      if (background?.type === 'video' && bgVideoRef.current?.readyState >= 2) {
        const vid = bgVideoRef.current;
        const scale = Math.max(W / vid.videoWidth, H / vid.videoHeight);
        const dw = vid.videoWidth * scale, dh = vid.videoHeight * scale;
        ctx.drawImage(vid, (W - dw) / 2, (H - dh) / 2, dw, dh);
        ctx.fillStyle = 'rgba(15,23,42,0.55)'; // darker than quote-loop — this frame carries a lot more text
        ctx.fillRect(0, 0, W, H);
      } else if (background?.type === 'photo' && bgImageRef.current?.complete && bgImageRef.current.naturalWidth) {
        const img = bgImageRef.current;
        const zoom = 1 + 0.08 * t;
        const scale = Math.max(W / img.naturalWidth, H / img.naturalHeight) * zoom;
        const dw = img.naturalWidth * scale, dh = img.naturalHeight * scale;
        ctx.drawImage(img, (W - dw) / 2, (H - dh) / 2, dw, dh);
        ctx.fillStyle = 'rgba(15,23,42,0.55)';
        ctx.fillRect(0, 0, W, H);
      } else {
        const angle = t * Math.PI * 0.4;
        const gradient = ctx.createLinearGradient(
          W / 2 + Math.cos(angle) * W, H / 2 + Math.sin(angle) * H,
          W / 2 - Math.cos(angle) * W, H / 2 - Math.sin(angle) * H
        );
        gradient.addColorStop(0, DARK);
        gradient.addColorStop(1, BRAND_BLUE);
        ctx.fillStyle = gradient;
        ctx.fillRect(0, 0, W, H);
      }

      // ── Subject/kicker tag ──
      ctx.textAlign = 'center';
      ctx.textBaseline = 'alphabetic';
      ctx.font = 'bold 30px Arial';
      ctx.fillStyle = BRAND_YELLOW;
      ctx.fillText((contentAsset.metadata?.subject || contentAsset.title || 'EXAM PREP').toUpperCase(), W / 2, 150);

      // ── Question (fades/scales in) ──
      const qIntroT = Math.min(1, elapsedMs / QUESTION_IN_MS);
      const qEased = 1 - Math.pow(1 - qIntroT, 3);
      ctx.font = '700 46px Arial';
      const qLines = wrapText(ctx, question, W - 140).slice(0, 5);
      const qLineH = 58;
      const qTop = 260;

      ctx.save();
      ctx.globalAlpha = qEased;
      ctx.fillStyle = '#ffffff';
      ctx.shadowColor = 'rgba(0,0,0,0.6)';
      ctx.shadowBlur = 10;
      qLines.forEach((line, i) => ctx.fillText(line, W / 2, qTop + i * qLineH + (1 - qEased) * 16));
      ctx.restore();

      // ── Options — each staggers in, then the correct one highlights ──
      const optionsTop = qTop + qLines.length * qLineH + 70;
      const optionH = 110;
      const optionGap = 24;
      ctx.font = '600 36px Arial';

      options.forEach((opt, i) => {
        const optStart = OPTIONS_START_MS + i * OPTION_STAGGER_MS;
        const optT = Math.min(1, Math.max(0, (elapsedMs - optStart) / 350));
        const optEased = 1 - Math.pow(1 - optT, 3);
        if (optEased <= 0) return;

        const y = optionsTop + i * (optionH + optionGap);
        const isCorrect = opt.id === correctOptionId;

        ctx.save();
        ctx.globalAlpha = optEased;
        const slideX = (1 - optEased) * 40;

        // Box
        ctx.fillStyle = revealed && isCorrect
          ? `rgba(34,197,94,${0.25 + 0.35 * revealEased})`
          : 'rgba(255,255,255,0.08)';
        ctx.strokeStyle = revealed && isCorrect ? GREEN : 'rgba(255,255,255,0.35)';
        ctx.lineWidth = revealed && isCorrect ? 4 : 2;
        const bx = 70 + slideX, bw = W - 140;
        ctx.beginPath();
        if (ctx.roundRect) ctx.roundRect(bx, y, bw, optionH, 18); else ctx.rect(bx, y, bw, optionH);
        ctx.fill();
        ctx.stroke();

        // Label circle
        ctx.textAlign = 'center';
        ctx.textBaseline = 'middle';
        ctx.fillStyle = revealed && isCorrect ? GREEN : 'rgba(255,255,255,0.9)';
        ctx.font = '800 34px Arial';
        ctx.fillText(opt.id, bx + 60, y + optionH / 2);

        // Option text (wrapped, left-aligned after the label)
        ctx.textAlign = 'left';
        ctx.font = '600 32px Arial';
        ctx.fillStyle = '#ffffff';
        const optLines = wrapText(ctx, opt.text, bw - 140).slice(0, 2);
        const optLineH = 36;
        const optTextTop = y + optionH / 2 - ((optLines.length - 1) * optLineH) / 2;
        optLines.forEach((line, li) => ctx.fillText(line, bx + 110, optTextTop + li * optLineH));

        if (revealed && isCorrect) {
          ctx.textAlign = 'right';
          ctx.font = '800 32px Arial';
          ctx.fillStyle = GREEN;
          ctx.globalAlpha = optEased * revealEased;
          ctx.fillText('✓', bx + bw - 34, y + optionH / 2 + 2);
        }
        ctx.restore();
      });

      // ── Explanation panel — fades in under the options once revealed ──
      if (explanation && revealEased > 0) {
        const explTop = optionsTop + options.length * (optionH + optionGap) + 40;
        ctx.font = '600 32px Arial';
        const explLines = wrapText(ctx, explanation, W - 200).slice(0, 6);
        const explLineH = 42;
        const panelH = explLines.length * explLineH + 80;

        ctx.save();
        ctx.globalAlpha = revealEased;
        ctx.fillStyle = 'rgba(15,23,42,0.75)';
        ctx.beginPath();
        if (ctx.roundRect) ctx.roundRect(70, explTop, W - 140, panelH, 20); else ctx.rect(70, explTop, W - 140, panelH);
        ctx.fill();
        ctx.strokeStyle = GREEN;
        ctx.lineWidth = 2;
        ctx.stroke();

        ctx.textAlign = 'left';
        ctx.font = 'bold 26px Arial';
        ctx.fillStyle = GREEN;
        ctx.fillText('WHY', 100, explTop + 44);

        ctx.font = '500 30px Arial';
        ctx.fillStyle = 'rgba(255,255,255,0.95)';
        explLines.forEach((line, i) => ctx.fillText(line, 100, explTop + 88 + i * explLineH));
        ctx.restore();
      }

      // Brand mark
      ctx.textAlign = 'left';
      ctx.font = 'bold 26px Arial';
      ctx.fillStyle = BRAND_YELLOW;
      ctx.fillText('SHINEY BRAIN ACADEMY', 50, H - 50);
    },
    [background, question, options, correctOptionId, explanation, contentAsset.metadata?.subject, contentAsset.title]
  );

  useEffect(() => {
    function loop() {
      const elapsed = status === 'recording' ? performance.now() - startTimeRef.current : 0;
      draw(elapsed);
      rafRef.current = requestAnimationFrame(loop);
    }
    if (status === 'recording') {
      rafRef.current = requestAnimationFrame(loop);
    } else {
      draw(REVEAL_AT_MS + REVEAL_DURATION_MS + 1500); // static idle frame — past the reveal, correct answer + explanation visible
    }
    return () => {
      if (rafRef.current) cancelAnimationFrame(rafRef.current);
    };
  }, [status, draw]);

  // ── Start / stop ─────────────────────────────────────────────────────
  const startRecording = async () => {
    setErrorMsg(null);
    setVideoBlobUrl(null);
    setVideoBlob(null);

    try {
      const AudioContextCls = window.AudioContext || window.webkitAudioContext;
      const audioCtx = new AudioContextCls();
      audioCtxRef.current = audioCtx;

      const dest = audioCtx.createMediaStreamDestination();

      if (tracks.length > 0 && audioRef.current) {
        const track = tracks[Math.floor(Math.random() * tracks.length)];
        audioRef.current.src = track;
        audioRef.current.loop = true;
        audioRef.current.currentTime = 0;
        await audioRef.current.play().catch(() => {});
        const source = audioCtx.createMediaElementSource(audioRef.current);
        source.connect(dest);
        source.connect(audioCtx.destination);
      }

      if (background?.type === 'video' && bgVideoRef.current) {
        bgVideoRef.current.currentTime = 0;
        bgVideoRef.current.play().catch(() => {});
      }

      const canvasStream = canvasRef.current.captureStream(30);
      const combined = new MediaStream([
        ...canvasStream.getVideoTracks(),
        ...dest.stream.getAudioTracks(),
      ]);

      // 9s clip vs quote-loop's 6s — bumped the bitrate down slightly so it
      // still comfortably clears most platforms' short-video size caps.
      const recorderOptions = { videoBitsPerSecond: 550_000, audioBitsPerSecond: 64_000 };
      const mimeType = pickMimeType();
      if (mimeType) recorderOptions.mimeType = mimeType;

      const recorder = new MediaRecorder(combined, recorderOptions);
      chunksRef.current = [];
      recorder.ondataavailable = (e) => {
        if (e.data.size > 0) chunksRef.current.push(e.data);
      };
      recorder.onstop = () => {
        const blob = new Blob(chunksRef.current, { type: mimeType || 'video/webm' });
        setVideoBlob(blob);
        setVideoBlobUrl(URL.createObjectURL(blob));
        setStatus('finished');
      };
      recorderRef.current = recorder;

      startTimeRef.current = performance.now();
      recorder.start();
      setStatus('recording');

      stopTimerRef.current = setTimeout(finishRecording, RECORD_SECONDS * 1000);
    } catch (err) {
      setStatus('error');
      setErrorMsg(`Could not start recording: ${err.message}`);
    }
  };

  function finishRecording() {
    if (stopTimerRef.current) clearTimeout(stopTimerRef.current);
    if (recorderRef.current && recorderRef.current.state !== 'inactive') recorderRef.current.stop();
    if (audioRef.current) audioRef.current.pause();
    if (bgVideoRef.current) bgVideoRef.current.pause();
    if (audioCtxRef.current) audioCtxRef.current.close().catch(() => {});
  }

  const cancelRecording = () => {
    if (stopTimerRef.current) clearTimeout(stopTimerRef.current);
    if (recorderRef.current) recorderRef.current.onstop = null;
    if (recorderRef.current && recorderRef.current.state !== 'inactive') recorderRef.current.stop();
    if (audioRef.current) audioRef.current.pause();
    if (bgVideoRef.current) bgVideoRef.current.pause();
    if (audioCtxRef.current) audioCtxRef.current.close().catch(() => {});
    setStatus('idle');
  };

  // ── Save: upload blob to storage, then tell the server to record it ──
  const saveToContentAsset = async () => {
    if (!videoBlob) return;
    setStatus('uploading');
    setErrorMsg(null);
    try {
      const supabase = createBrowserClient();
      const ext = extensionForMimeType(videoBlob.type);
      const path = `${contentAsset.id}/${Date.now()}.${ext}`;

      const { error: uploadError } = await supabase.storage
        .from(BUCKET)
        .upload(path, videoBlob, { contentType: videoBlob.type || 'video/webm', upsert: true });
      if (uploadError) throw uploadError;

      const { data: urlData } = supabase.storage.from(BUCKET).getPublicUrl(path);

      const res = await fetch('/api/admin/past-question-loops/save', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          contentAssetId: contentAsset.id,
          videoUrl: urlData.publicUrl,
          durationSeconds: RECORD_SECONDS,
        }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error || 'Save failed');

      setStatus('saved');
      onSaved?.(urlData.publicUrl);
    } catch (err) {
      setStatus('finished');
      setErrorMsg(err.message);
    }
  };

  return (
    <div className="space-y-4">
      <canvas
        ref={canvasRef}
        width={CANVAS_W}
        height={CANVAS_H}
        className="w-full max-w-[280px] aspect-[9/16] mx-auto rounded-2xl border shadow-sm bg-black"
      />
      <video ref={bgVideoRef} muted playsInline className="hidden" />
      <audio ref={audioRef} crossOrigin="anonymous" className="hidden" />

      <p className="text-xs text-gray-500 text-center">
        {background?.type === 'video' && `Real footage background (${background.source}).`}
        {background?.type === 'photo' && `Photo background with zoom (${background.source}).`}
        {!background && 'No background candidate found — recording on an animated brand gradient.'}
        {' '}Records a {RECORD_SECONDS}s question reveal{tracks.length === 0 ? ' — no music tracks found, clip will be silent' : ''}.
      </p>

      {errorMsg && <p className="text-sm text-red-600 text-center">⚠️ {errorMsg}</p>}
      {!bgReady && status === 'idle' && (
        <p className="text-xs text-gray-400 text-center">Loading background…</p>
      )}

      <div className="flex justify-center gap-2">
        {status === 'idle' && (
          <button
            onClick={startRecording}
            disabled={!bgReady}
            className="bg-brand-blue text-white px-5 py-2.5 rounded-xl text-sm font-bold hover:opacity-90 disabled:opacity-50"
          >
            🔴 Start Recording
          </button>
        )}
        {status === 'recording' && (
          <button
            onClick={cancelRecording}
            className="bg-red-100 text-red-600 px-5 py-2.5 rounded-xl text-sm font-bold hover:bg-red-200"
          >
            ⏹ Cancel
          </button>
        )}
        {(status === 'finished' || status === 'saved') && videoBlobUrl && (
          <>
            <a
              href={videoBlobUrl}
              download={`${(contentAsset.title || 'past-question-loop').replace(/[^a-z0-9]+/gi, '-').toLowerCase()}.${extensionForMimeType(videoBlob?.type)}`}
              className="bg-gray-100 text-gray-700 px-5 py-2.5 rounded-xl text-sm font-bold hover:bg-gray-200"
            >
              ⬇ Download
            </a>
            {status === 'finished' ? (
              <button
                onClick={saveToContentAsset}
                className="bg-emerald-600 text-white px-5 py-2.5 rounded-xl text-sm font-bold hover:opacity-90"
              >
                💾 Save
              </button>
            ) : (
              <span className="text-sm font-bold text-emerald-600 px-3 py-2.5">✓ Saved</span>
            )}
          </>
        )}
        {status === 'uploading' && (
          <span className="text-sm font-bold text-gray-500 px-3 py-2.5">Uploading…</span>
        )}
      </div>
    </div>
  );
}
