'use client';

// components/TeachingLoopRecorder.js
//
// Renders one teaching_loop content_assets row (a ~2 minute script of short
// text cards + one background candidate, generated by
// /api/admin/teaching-loops/generate) into a real vertical video: real
// stock footage or a photo with a slow continuous Ken Burns zoom (or an
// animated brand gradient if no background was found) behind an
// Instagram-Stories-style progress bar and one text card at a time,
// fading/sliding through the whole script, + background music — entirely
// in the browser via <canvas> + Web Audio API + MediaRecorder. Exact same
// technique as QuoteLoopRecorder.js/PastQuestionLoopRecorder.js, just a
// longer, multi-segment timeline instead of one fixed clip — no Remotion,
// no laptop render worker, no server-side rendering at all.

import { useRef, useState, useEffect, useCallback, useMemo } from 'react';
import { createBrowserClient } from '@/lib/supabase';

const CANVAS_W = 1080;
const CANVAS_H = 1920; // 9:16 — TikTok / IG Reels / YouTube Shorts
const BRAND_BLUE = '#1a73e8';
const BRAND_YELLOW = '#FFCC00';
const DARK = '#0f172a';
const BUCKET = 'teaching-loops'; // create this bucket in Supabase storage (public read, authenticated upload) — same policy shape as quote-loops — before first use
const MIN_TOTAL_SECONDS = 80;
const MAX_TOTAL_SECONDS = 160;
const CARD_TRANSITION_MS = 350; // fade/slide in and out at each card's edges

function wrapText(ctx, text, maxWidth) {
  const words = String(text || '').split(' ');
  const lines = [];
  let current = '';
  for (const word of words) {
    const test = current ? `${current} ${word}` : word;
    if (ctx.measureText(test).width > maxWidth && current) {
      lines.push(current);
      current = word;
    } else {
      current = test;
    }
  }
  if (current) lines.push(current);
  return lines;
}

function pickMimeType() {
  const candidates = [
    // Real MP4 muxing (H.264 + AAC) is what Instagram/TikTok's video
    // processing actually wants — same list/order as QuoteLoopRecorder.js.
    'video/mp4;codecs=avc1.42E01E,mp4a.40.2',
    'video/mp4;codecs=avc1,mp4a.40.2',
    'video/mp4',
    'video/webm;codecs=vp9,opus',
    'video/webm;codecs=vp8,opus',
    'video/webm',
  ];
  for (const type of candidates) {
    if (typeof MediaRecorder !== 'undefined' && MediaRecorder.isTypeSupported(type)) return type;
  }
  return '';
}

function extensionForMimeType(mimeType) {
  return (mimeType || '').includes('mp4') ? 'mp4' : 'webm';
}

/**
 * @param {Object} props
 * @param {Object} props.contentAsset - a content_assets row (id, title, metadata.{segments, background})
 * @param {(videoUrl: string) => void} [props.onSaved]
 */
export default function TeachingLoopRecorder({ contentAsset, onSaved }) {
  const canvasRef = useRef(null);
  const bgVideoRef = useRef(null);
  const bgImageRef = useRef(null);
  const audioRef = useRef(null);
  const audioCtxRef = useRef(null);
  const rafRef = useRef(null);
  const recorderRef = useRef(null);
  const chunksRef = useRef([]);
  const startTimeRef = useRef(0);
  const stopTimerRef = useRef(null);

  const [status, setStatus] = useState('idle'); // idle | recording | finished | uploading | saved | error
  const [videoBlobUrl, setVideoBlobUrl] = useState(null);
  const [videoBlob, setVideoBlob] = useState(null);
  const [errorMsg, setErrorMsg] = useState(null);
  const [tracks, setTracks] = useState([]);
  const [bgReady, setBgReady] = useState(false);
  const [elapsedDisplay, setElapsedDisplay] = useState(0);

  const background = contentAsset.metadata?.background || null;
  const rawSegments = useMemo(() => contentAsset.metadata?.segments || [], [contentAsset.metadata]);

  // Segments carry a holdSeconds estimate from generate/route.js — clamp
  // the total so a pathological script (all very short/long cards) can't
  // produce an absurdly short or multi-minute-plus recording.
  const { segments, cumulativeStarts, totalSeconds } = useMemo(() => {
    if (rawSegments.length === 0) return { segments: [], cumulativeStarts: [], totalSeconds: MIN_TOTAL_SECONDS };
    const rawTotal = rawSegments.reduce((sum, s) => sum + (s.holdSeconds || 8), 0);
    const clampedTotal = Math.min(MAX_TOTAL_SECONDS, Math.max(MIN_TOTAL_SECONDS, rawTotal));
    const scale = rawTotal > 0 ? clampedTotal / rawTotal : 1;
    const scaled = rawSegments.map((s) => Math.max(4, (s.holdSeconds || 8) * scale));
    const starts = [];
    let acc = 0;
    for (const dur of scaled) {
      starts.push(acc);
      acc += dur;
    }
    return { segments: rawSegments.map((s, i) => ({ ...s, holdSeconds: scaled[i] })), cumulativeStarts: starts, totalSeconds: acc };
  }, [rawSegments]);

  // ── Discover music tracks + preload background on mount ────────────────
  // Reuses the quote-loops music library rather than duplicating a second
  // copy of the same royalty-cleared tracks under a second folder.
  useEffect(() => {
    fetch('/api/admin/quote-loops/audio-list')
      .then((r) => r.json())
      .then((d) => setTracks(d.tracks || []))
      .catch(() => setTracks([]));

    if (background?.type === 'photo') {
      const img = new Image();
      img.crossOrigin = 'anonymous';
      img.onload = () => setBgReady(true);
      img.onerror = () => setBgReady(true);
      img.src = background.url;
      bgImageRef.current = img;
    } else if (background?.type === 'video') {
      const vid = bgVideoRef.current;
      if (vid) {
        vid.src = background.url;
        vid.crossOrigin = 'anonymous';
        vid.muted = true;
        vid.loop = true;
        vid.oncanplaythrough = () => setBgReady(true);
        vid.onerror = () => setBgReady(true);
        vid.load();
      }
    } else {
      setBgReady(true);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // Which segment index is "current" for a given elapsed time.
  const segmentIndexAt = useCallback(
    (elapsedMs) => {
      const elapsedS = elapsedMs / 1000;
      for (let i = cumulativeStarts.length - 1; i >= 0; i--) {
        if (elapsedS >= cumulativeStarts[i]) return i;
      }
      return 0;
    },
    [cumulativeStarts]
  );

  // ── Drawing ─────────────────────────────────────────────────────────────
  const draw = useCallback(
    (elapsedMs) => {
      const canvas = canvasRef.current;
      if (!canvas || segments.length === 0) return;
      const ctx = canvas.getContext('2d');
      const W = CANVAS_W, H = CANVAS_H;
      const t = Math.min(1, elapsedMs / (totalSeconds * 1000)); // 0→1 over the WHOLE clip, for a continuous background zoom

      // ── Background layer (continuous zoom across the whole 2 minutes,
      //    not per-segment, so it doesn't look like it's resetting/jumping) ──
      if (background?.type === 'video' && bgVideoRef.current?.readyState >= 2) {
        const vid = bgVideoRef.current;
        const scale = Math.max(W / vid.videoWidth, H / vid.videoHeight);
        const dw = vid.videoWidth * scale, dh = vid.videoHeight * scale;
        ctx.drawImage(vid, (W - dw) / 2, (H - dh) / 2, dw, dh);
        ctx.fillStyle = 'rgba(15,23,42,0.5)';
        ctx.fillRect(0, 0, W, H);
      } else if (background?.type === 'photo' && bgImageRef.current?.complete && bgImageRef.current.naturalWidth) {
        const img = bgImageRef.current;
        const zoom = 1 + 0.15 * t;
        const scale = Math.max(W / img.naturalWidth, H / img.naturalHeight) * zoom;
        const dw = img.naturalWidth * scale, dh = img.naturalHeight * scale;
        ctx.drawImage(img, (W - dw) / 2, (H - dh) / 2, dw, dh);
        ctx.fillStyle = 'rgba(15,23,42,0.5)';
        ctx.fillRect(0, 0, W, H);
      } else {
        const angle = t * Math.PI * 2; // slow full rotation over the whole clip
        const gradient = ctx.createLinearGradient(
          W / 2 + Math.cos(angle) * W, H / 2 + Math.sin(angle) * H,
          W / 2 - Math.cos(angle) * W, H / 2 - Math.sin(angle) * H
        );
        gradient.addColorStop(0, DARK);
        gradient.addColorStop(1, BRAND_BLUE);
        ctx.fillStyle = gradient;
        ctx.fillRect(0, 0, W, H);
      }

      // ── Instagram-Stories-style progress bar: one segment per tick ──
      const barY = 70, barGap = 8, barH = 6;
      const barW = (W - 80 - barGap * (segments.length - 1)) / segments.length;
      const activeIndex = segmentIndexAt(elapsedMs);
      segments.forEach((_, i) => {
        const x = 40 + i * (barW + barGap);
        ctx.fillStyle = 'rgba(255,255,255,0.3)';
        ctx.fillRect(x, barY, barW, barH);
        if (i < activeIndex) {
          ctx.fillStyle = '#ffffff';
          ctx.fillRect(x, barY, barW, barH);
        } else if (i === activeIndex) {
          const segStart = cumulativeStarts[i] * 1000;
          const segDur = (segments[i].holdSeconds || 8) * 1000;
          const frac = Math.min(1, Math.max(0, (elapsedMs - segStart) / segDur));
          ctx.fillStyle = '#ffffff';
          ctx.fillRect(x, barY, barW * frac, barH);
        }
      });

      // ── Kicker: topic name, small, top-left ──
      ctx.textAlign = 'left';
      ctx.textBaseline = 'alphabetic';
      ctx.font = 'bold 26px Arial';
      ctx.fillStyle = 'rgba(255,255,255,0.75)';
      ctx.fillText('SHINEY BRAIN ACADEMY', 40, 130);

      // ── Current text card ──
      const seg = segments[activeIndex];
      if (!seg) return;
      const segStartMs = cumulativeStarts[activeIndex] * 1000;
      const segDurMs = (seg.holdSeconds || 8) * 1000;
      const localMs = elapsedMs - segStartMs;

      const inT = Math.min(1, localMs / CARD_TRANSITION_MS);
      const inEased = 1 - Math.pow(1 - inT, 3);
      const outStart = segDurMs - CARD_TRANSITION_MS;
      const outT = localMs > outStart ? Math.min(1, (localMs - outStart) / CARD_TRANSITION_MS) : 0;
      const outEased = 1 - Math.pow(1 - outT, 3);
      const alpha = Math.max(0, inEased - outEased);
      const slideY = (1 - inEased) * 40 - outEased * -20;

      // Label pill
      const label = (seg.label || '').toUpperCase();
      ctx.font = 'bold 30px Arial';

      // Card text
      ctx.font = '800 58px Arial';
      const lines = wrapText(ctx, seg.text, W - 160).slice(0, 6);
      const lineH = 70;
      const blockH = lines.length * lineH + (label ? 80 : 0);
      const centerY = H * 0.55;
      const topY = centerY - blockH / 2 + slideY;

      // Scrim behind the card so text reads over any footage
      const scrimTop = topY - 90;
      const scrimH = blockH + 180;
      const scrimGrad = ctx.createLinearGradient(0, scrimTop, 0, scrimTop + scrimH);
      scrimGrad.addColorStop(0, 'rgba(15,23,42,0)');
      scrimGrad.addColorStop(0.15, `rgba(15,23,42,${0.6 * alpha})`);
      scrimGrad.addColorStop(0.85, `rgba(15,23,42,${0.6 * alpha})`);
      scrimGrad.addColorStop(1, 'rgba(15,23,42,0)');
      ctx.fillStyle = scrimGrad;
      ctx.fillRect(0, scrimTop, W, scrimH);

      ctx.save();
      ctx.globalAlpha = alpha;

      let cursorY = topY;
      if (label) {
        ctx.textAlign = 'center';
        ctx.font = 'bold 30px Arial';
        ctx.fillStyle = BRAND_YELLOW;
        ctx.fillText(label, W / 2, cursorY);
        cursorY += 80;
      }

      ctx.textAlign = 'center';
      ctx.textBaseline = 'alphabetic';
      ctx.font = '800 58px Arial';
      ctx.fillStyle = '#ffffff';
      ctx.shadowColor = 'rgba(0,0,0,0.6)';
      ctx.shadowBlur = 12;
      lines.forEach((line, i) => {
        ctx.fillText(line, W / 2, cursorY + i * lineH);
      });
      ctx.restore();

      // Segment counter, bottom
      ctx.textAlign = 'right';
      ctx.font = 'bold 26px Arial';
      ctx.fillStyle = 'rgba(255,255,255,0.6)';
      ctx.fillText(`${activeIndex + 1}/${segments.length}`, W - 40, H - 50);
    },
    [background, segments, cumulativeStarts, totalSeconds, segmentIndexAt]
  );

  useEffect(() => {
    function loop() {
      const elapsed = status === 'recording' ? performance.now() - startTimeRef.current : 0;
      draw(elapsed);
      if (status === 'recording') setElapsedDisplay(elapsed / 1000);
      rafRef.current = requestAnimationFrame(loop);
    }
    if (status === 'recording') {
      rafRef.current = requestAnimationFrame(loop);
    } else {
      draw(CARD_TRANSITION_MS + 100); // static idle frame — first card visible, past its fade-in
    }
    return () => {
      if (rafRef.current) cancelAnimationFrame(rafRef.current);
    };
  }, [status, draw]);

  // ── Start / stop ─────────────────────────────────────────────────────
  const startRecording = async () => {
    setErrorMsg(null);
    setVideoBlobUrl(null);
    setVideoBlob(null);

    try {
      const AudioContextCls = window.AudioContext || window.webkitAudioContext;
      const audioCtx = new AudioContextCls();
      audioCtxRef.current = audioCtx;

      const dest = audioCtx.createMediaStreamDestination();

      if (tracks.length > 0 && audioRef.current) {
        const track = tracks[Math.floor(Math.random() * tracks.length)];
        audioRef.current.src = track;
        audioRef.current.loop = true;
        audioRef.current.currentTime = 0;
        await audioRef.current.play().catch(() => {});
        const source = audioCtx.createMediaElementSource(audioRef.current);
        source.connect(dest);
        source.connect(audioCtx.destination);
      }

      if (background?.type === 'video' && bgVideoRef.current) {
        bgVideoRef.current.currentTime = 0;
        bgVideoRef.current.play().catch(() => {});
      }

      const canvasStream = canvasRef.current.captureStream(30);
      const combined = new MediaStream([
        ...canvasStream.getVideoTracks(),
        ...dest.stream.getAudioTracks(),
      ]);

      // Lower bitrate than quote-loop's 6s clip — at ~2 minutes, 700kbps
      // would produce a much bigger file for not much visible gain since
      // most of the frame is a static text card, not fast motion.
      const recorderOptions = { videoBitsPerSecond: 450_000, audioBitsPerSecond: 96_000 };
      const mimeType = pickMimeType();
      if (mimeType) recorderOptions.mimeType = mimeType;

      const recorder = new MediaRecorder(combined, recorderOptions);
      chunksRef.current = [];
      recorder.ondataavailable = (e) => {
        if (e.data.size > 0) chunksRef.current.push(e.data);
      };
      recorder.onstop = () => {
        const blob = new Blob(chunksRef.current, { type: mimeType || 'video/webm' });
        setVideoBlob(blob);
        setVideoBlobUrl(URL.createObjectURL(blob));
        setStatus('finished');
      };
      recorderRef.current = recorder;

      startTimeRef.current = performance.now();
      recorder.start();
      setStatus('recording');

      stopTimerRef.current = setTimeout(finishRecording, totalSeconds * 1000);
    } catch (err) {
      setStatus('error');
      setErrorMsg(`Could not start recording: ${err.message}`);
    }
  };

  function finishRecording() {
    if (stopTimerRef.current) clearTimeout(stopTimerRef.current);
    if (recorderRef.current && recorderRef.current.state !== 'inactive') recorderRef.current.stop();
    if (audioRef.current) audioRef.current.pause();
    if (bgVideoRef.current) bgVideoRef.current.pause();
    if (audioCtxRef.current) audioCtxRef.current.close().catch(() => {});
  }

  const cancelRecording = () => {
    if (stopTimerRef.current) clearTimeout(stopTimerRef.current);
    if (recorderRef.current) recorderRef.current.onstop = null;
    if (recorderRef.current && recorderRef.current.state !== 'inactive') recorderRef.current.stop();
    if (audioRef.current) audioRef.current.pause();
    if (bgVideoRef.current) bgVideoRef.current.pause();
    if (audioCtxRef.current) audioCtxRef.current.close().catch(() => {});
    setStatus('idle');
  };

  // ── Save: upload blob to storage, then tell the server to record it ──
  const saveToContentAsset = async () => {
    if (!videoBlob) return;
    setStatus('uploading');
    setErrorMsg(null);
    try {
      const supabase = createBrowserClient();
      const ext = extensionForMimeType(videoBlob.type);
      const path = `${contentAsset.id}/${Date.now()}.${ext}`;

      const { error: uploadError } = await supabase.storage
        .from(BUCKET)
        .upload(path, videoBlob, { contentType: videoBlob.type || 'video/webm', upsert: true });
      if (uploadError) throw uploadError;

      const { data: urlData } = supabase.storage.from(BUCKET).getPublicUrl(path);

      const res = await fetch('/api/admin/teaching-loops/save', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          contentAssetId: contentAsset.id,
          videoUrl: urlData.publicUrl,
          durationSeconds: Math.round(totalSeconds),
        }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error || 'Save failed');

      setStatus('saved');
      onSaved?.(urlData.publicUrl);
    } catch (err) {
      setStatus('finished');
      setErrorMsg(err.message);
    }
  };

  if (segments.length === 0) {
    return <p className="text-sm text-red-600 text-center">This draft has no script segments to record.</p>;
  }

  return (
    <div className="space-y-4">
      <canvas
        ref={canvasRef}
        width={CANVAS_W}
        height={CANVAS_H}
        className="w-full max-w-[280px] aspect-[9/16] mx-auto rounded-2xl border shadow-sm bg-black"
      />
      <video ref={bgVideoRef} muted playsInline className="hidden" />
      <audio ref={audioRef} crossOrigin="anonymous" className="hidden" />

      <p className="text-xs text-gray-500 text-center">
        {background?.type === 'video' && `Real footage background (${background.source}).`}
        {background?.type === 'photo' && `Photo background with zoom (${background.source}).`}
        {!background && 'No background candidate found — recording on an animated brand gradient.'}
        {' '}Records a ~{Math.round(totalSeconds)}s, {segments.length}-card teaching loop
        {tracks.length === 0 ? ' — no music tracks found in public/audio/quote-loops yet, clip will be silent' : ''}.
      </p>

      {status === 'recording' && (
        <p className="text-xs text-center text-gray-400">
          Recording… {Math.round(elapsedDisplay)}s / {Math.round(totalSeconds)}s
        </p>
      )}

      {errorMsg && <p className="text-sm text-red-600 text-center">⚠️ {errorMsg}</p>}
      {!bgReady && status === 'idle' && (
        <p className="text-xs text-gray-400 text-center">Loading background…</p>
      )}

      <div className="flex justify-center gap-2">
        {status === 'idle' && (
          <button
            onClick={startRecording}
            disabled={!bgReady}
            className="bg-brand-blue text-white px-5 py-2.5 rounded-xl text-sm font-bold hover:opacity-90 disabled:opacity-50"
          >
            🔴 Start Recording
          </button>
        )}
        {status === 'recording' && (
          <button
            onClick={cancelRecording}
            className="bg-red-100 text-red-600 px-5 py-2.5 rounded-xl text-sm font-bold hover:bg-red-200"
          >
            ⏹ Cancel
          </button>
        )}
        {(status === 'finished' || status === 'saved') && videoBlobUrl && (
          <>
            <a
              href={videoBlobUrl}
              download={`${(contentAsset.title || 'teaching-loop').replace(/[^a-z0-9]+/gi, '-').toLowerCase()}.${extensionForMimeType(videoBlob?.type)}`}
              className="bg-gray-100 text-gray-700 px-5 py-2.5 rounded-xl text-sm font-bold hover:bg-gray-200"
            >
              ⬇ Download
            </a>
            {status === 'finished' ? (
              <button
                onClick={saveToContentAsset}
                className="bg-emerald-600 text-white px-5 py-2.5 rounded-xl text-sm font-bold hover:opacity-90"
              >
                💾 Save
              </button>
            ) : (
              <span className="text-sm font-bold text-emerald-600 px-3 py-2.5">✓ Saved</span>
            )}
          </>
        )}
        {status === 'uploading' && (
          <span className="text-sm font-bold text-gray-500 px-3 py-2.5">Uploading…</span>
        )}
      </div>
    </div>
  );
}
