// lib/journeyEngine.js
//
// Journey Engine — pure logic, no UI, no React.
//
// v2 — corrected after finding the real schema differs from an earlier
// draft of this file. Key corrections, discovered by reading the actual
// current repo (app/syllabus/page.js, app/quizzes/[id]/page.js,
// app/api/boss-battles/[draftId]/publish/route.js, etc.):
//
// 1. Entry point is a `game_topic_id`, not a `knowledge_asset_id`. The
//    World Map (app/syllabus/page.js) links to game_topics rows, which are
//    a published, student-safe projection of a knowledge_asset. This
//    engine resolves game_topic -> knowledge_asset_id internally.
// 2. student_topic_progress is keyed by (student_id, game_topic_id), not
//    knowledge_asset_id.
// 3. Quiz content generated by the content engine lives in `quiz_drafts`
//    (status='published', knowledge_asset_id=X) and is played at
//    /quizzes/[id]?draft=true — a *different* route from /quiz/[id],
//    which only serves manually-authored quizzes from the `quizzes`
//    table. quiz_drafts never gets merged into `quizzes`.
// 4. Boss battle content generated by the content engine lives in
//    `boss_battle_drafts` (status='draft'), but ON PUBLISH it copies into
//    the live `boss_battles` table (see app/api/boss-battles/[draftId]/
//    publish/route.js) and the draft row is stamped with the resulting
//    `boss_battle_id`. So: find the draft by knowledge_asset_id, then use
//    its `boss_battle_id` to link to the live, already-gamified /boss
//    experience and to check `boss_attempts`.
// 5. Flashcards are the simplest case: flashcard_drafts IS the
//    student-facing table (status='published', knowledge_asset_id=X),
//    played at /flashcards/[id]. No separate live table.
// 6. study_note / video / podcast paths (study_note_drafts, video_scripts,
//    podcast_episodes) were NOT re-verified in this pass — they were
//    confirmed to exist as tables earlier but their student-facing routes
//    and publish flow were not traced the way quiz/boss/flashcards were.
//    Treat those three as provisional until checked the same way.
// 7. `game_topics`, `student_topic_progress`, and `knowledge_asset_missions`
//    are not in supabase/migrations — verify the live schema (especially
//    the unique constraint used by the upsert below) before shipping.

const DEFAULT_STEP_ORDER = {
  study_note: 1,
  video: 2,
  podcast: 3,
  flashcards: 4,
  topic_games: 5, // the existing /games/[gameTopicId] page (Sequence Builder,
                  // Sequence Memory, Definition Match) — already built,
                  // already topic-scoped, currently awards no XP itself.
  quiz: 6,
  boss_battle: 7,
};

const STEP_XP = {
  study_note: 10,
  video: 10,
  podcast: 10,
  flashcards: 15,
  topic_games: 15,
  quiz: 20,
  boss_battle: 40,
};

const MISSION_COMPLETE_BONUS_XP = 50;

/** Resolve the World Map's game_topic into its source knowledge_asset,
 * plus the fields the Mission Briefing needs directly. */
async function fetchGameTopic(supabase, gameTopicId) {
  const { data, error } = await supabase
    .from('game_topics')
    .select('id, knowledge_asset_id, title, subject, definitions, order_index')
    .eq('id', gameTopicId)
    .single();

  if (error || !data) {
    throw new Error(`Journey Engine: could not load game_topic ${gameTopicId}: ${error?.message || 'not found'}`);
  }
  return data;
}

/** Objectives/exam type/duration live on the source knowledge_asset, not
 * the published game_topics projection — fetch separately for the
 * briefing screen. Optional: if these columns don't exist, the briefing
 * just shows fewer details rather than failing. */
async function fetchAssetBriefingFields(supabase, knowledgeAssetId) {
  const { data } = await supabase
    .from('knowledge_assets')
    .select('learning_objectives, exam_type, estimated_duration_minutes')
    .eq('id', knowledgeAssetId)
    .maybeSingle();
  return data || {};
}

/** Optional hand-authored override — see supabase/migrations/
 * 20260730_knowledge_asset_missions.sql. Keyed by knowledge_asset_id since
 * it's an authoring-time concept tied to the source content, not the
 * published projection. Fails soft if the table or row doesn't exist. */
async function fetchCustomMissionOrder(supabase, knowledgeAssetId) {
  try {
    const { data, error } = await supabase
      .from('knowledge_asset_missions')
      .select('step_order')
      .eq('knowledge_asset_id', knowledgeAssetId)
      .maybeSingle();
    if (error || !data) return null;
    return Array.isArray(data.step_order) ? data.step_order : null;
  } catch (e) {
    return null;
  }
}

/**
 * Query each content system for this knowledge_asset. Each activity type
 * has its own real shape (see corrections in the file header) — this is
 * not a uniform "one column per type" lookup.
 */
async function fetchAvailableActivities(supabase, knowledgeAssetId, gameTopic) {
  const activities = {};

  const [studyNoteRes, videoRes, podcastRes, flashcardRes, quizDraftRes, bossDraftRes] = await Promise.all([
    supabase
      .from('study_note_drafts') // provisional — see file header point 6
      .select('id, title, status')
      .eq('knowledge_asset_id', knowledgeAssetId)
      .eq('status', 'published')
      .maybeSingle(),
    supabase
      .from('video_scripts') // provisional — see file header point 6
      .select('id, title')
      .eq('knowledge_asset_id', knowledgeAssetId)
      .maybeSingle(),
    supabase
      .from('podcast_episodes') // provisional — see file header point 6
      .select('id, title')
      .eq('knowledge_asset_id', knowledgeAssetId)
      .maybeSingle(),
    supabase
      .from('flashcard_drafts')
      .select('id, keyword, cards')
      .eq('knowledge_asset_id', knowledgeAssetId)
      .eq('status', 'published')
      .maybeSingle(),
    supabase
      .from('quiz_drafts')
      .select('id, keyword, questions, passing_score')
      .eq('knowledge_asset_id', knowledgeAssetId)
      .eq('status', 'published')
      .maybeSingle(),
    supabase
      .from('boss_battle_drafts')
      .select('id, name, boss_battle_id, status')
      .eq('knowledge_asset_id', knowledgeAssetId)
      .eq('status', 'published')
      .maybeSingle(),
  ]);

  if (studyNoteRes?.data) activities.study_note = { ref: studyNoteRes.data };
  if (videoRes?.data) activities.video = { ref: videoRes.data };
  if (podcastRes?.data) activities.podcast = { ref: podcastRes.data };
  if (flashcardRes?.data) activities.flashcards = { ref: flashcardRes.data };

  if (quizDraftRes?.data) {
    // ref.id here is the quiz_drafts id — the id used by /quizzes/[id]?draft=true
    activities.quiz = { ref: quizDraftRes.data };
  }

  if (bossDraftRes?.data?.boss_battle_id) {
    // Route to the LIVE boss_battles id, not the draft id — that's what
    // /boss and boss_attempts actually use once published.
    activities.boss_battle = {
      ref: { id: bossDraftRes.data.boss_battle_id, name: bossDraftRes.data.name },
    };
  }

  // The existing /games/[gameTopicId] page (Sequence Builder/Memory/
  // Definition Match) is already topic-scoped via game_topics itself —
  // no extra query needed, just check it has enough content the same way
  // components/games/GamesClient.js does.
  const hasDefinitions = Array.isArray(gameTopic.definitions) && gameTopic.definitions.filter((d) => d?.term && d?.definition).length >= 2;
  if (hasDefinitions) {
    activities.topic_games = { ref: { id: gameTopic.id } };
  } else {
    // Even without definitions, a game_topic might still have sequence
    // steps (checked via game_sequence_steps) — the engine doesn't query
    // that table separately here since GamesClient itself will just show
    // fewer tabs; treating "has definitions" as the trigger is a slight
    // simplification. Fine for v1; revisit if topics commonly have
    // sequence steps but zero definitions.
  }

  return activities;
}

function buildSteps(availableActivities, customOrder) {
  const order = customOrder && customOrder.length
    ? customOrder
    : Object.keys(DEFAULT_STEP_ORDER).sort((a, b) => DEFAULT_STEP_ORDER[a] - DEFAULT_STEP_ORDER[b]);

  return order
    .filter((activityType) => availableActivities[activityType])
    .map((activityType) => ({
      type: activityType,
      ref: availableActivities[activityType].ref,
      xp: STEP_XP[activityType] ?? 10,
      completed: false,
    }));
}

/** Public entry point. gameTopicId is the id the World Map already links
 * to (game_topics.id). Returns a plain, serializable Mission object. */
export async function buildMission(supabase, gameTopicId) {
  const gameTopic = await fetchGameTopic(supabase, gameTopicId);
  const knowledgeAssetId = gameTopic.knowledge_asset_id;

  const [briefingFields, customOrder, availableActivities] = await Promise.all([
    fetchAssetBriefingFields(supabase, knowledgeAssetId),
    fetchCustomMissionOrder(supabase, knowledgeAssetId),
    fetchAvailableActivities(supabase, knowledgeAssetId, gameTopic),
  ]);

  const steps = buildSteps(availableActivities, customOrder);
  const totalStepXp = steps.reduce((sum, s) => sum + s.xp, 0);

  return {
    gameTopicId: gameTopic.id,
    knowledgeAssetId,
    title: gameTopic.title,
    subject: gameTopic.subject || 'General',
    objectives: Array.isArray(briefingFields.learning_objectives) ? briefingFields.learning_objectives : [],
    examType: Array.isArray(briefingFields.exam_type) ? briefingFields.exam_type : [],
    estimatedMinutes: briefingFields.estimated_duration_minutes ?? null,
    rewards: {
      stepXp: totalStepXp,
      bonusXp: MISSION_COMPLETE_BONUS_XP,
      totalXp: totalStepXp + MISSION_COMPLETE_BONUS_XP,
    },
    steps,
    isEmpty: steps.length === 0,
  };
}

function computeTier(signals = {}) {
  const { quizScorePct, bossBattleWon } = signals;
  if (bossBattleWon && (quizScorePct ?? 0) >= 80) return 'gold';
  if ((quizScorePct ?? 0) >= 60) return 'silver';
  return 'bronze';
}

/**
 * Writes mission completion back to student_topic_progress, keyed by
 * (student_id, game_topic_id) — matching the real table shape confirmed
 * from app/syllabus/page.js. onConflict target assumes a unique
 * constraint on (student_id, game_topic_id); verify against the live
 * table before shipping, since this table isn't in migrations.
 */
export async function recordMissionResult(supabase, { studentId, gameTopicId, signals }) {
  const tier = computeTier(signals);

  const update = {
    student_id: studentId,
    game_topic_id: gameTopicId,
    bronze_earned: true,
    silver_earned: tier === 'silver' || tier === 'gold',
    gold_earned: tier === 'gold',
  };

  const { data, error } = await supabase
    .from('student_topic_progress')
    .upsert(update, { onConflict: 'student_id,game_topic_id' })
    .select()
    .single();

  if (error) {
    throw new Error(`Journey Engine: failed to write student_topic_progress: ${error.message}`);
  }

  return { tier, progress: data };
}
