'use client';

import { useState, useEffect } from 'react';
import Link from 'next/link';
import { supabase } from '@/lib/supabase-client';

export default function BlogDraftsPage() {
  const [drafts, setDrafts] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchDrafts();
  }, []);

  async function fetchDrafts() {
    setLoading(true);
    const { data, error } = await supabase
      .from('content_drafts')
      .select('*')
      .neq('status', 'published')
      .order('created_at', { ascending: false });

    if (error) {
      console.error('Error fetching drafts:', error);
      alert('Error loading drafts: ' + error.message);
    } else {
      setDrafts(data || []);
    }
    setLoading(false);
  }

  async function publishDraft(id) {
    if (!confirm('Publish this post? It will go live on the blog.')) return;
    const { error } = await supabase
      .from('content_drafts')
      .update({ status: 'published', published_at: new Date().toISOString() })
      .eq('id', id);
    if (error) {
      alert('Publish failed: ' + error.message);
    } else {
      fetchDrafts();
    }
  }

  async function deleteDraft(id) {
    if (!confirm('Delete this draft permanently?')) return;
    const { error } = await supabase.from('content_drafts').delete().eq('id', id);
    if (error) {
      alert('Delete failed: ' + error.message);
    } else {
      fetchDrafts();
    }
  }

  return (
    <div className="p-6 max-w-6xl mx-auto">
      <div className="flex justify-between items-center mb-2">
        <h1 className="text-2xl font-bold text-gray-900">📝 Blog Drafts</h1>
        <Link href="/admin/blog" className="text-sm text-blue-600 hover:underline">
          View published posts →
        </Link>
      </div>
      <p className="text-sm text-gray-500 mb-6">
        Posts generated by the blog engine (or saved as drafts) land here first. Review, then publish.
      </p>

      {loading ? (
        <div className="space-y-3">
          {[1, 2, 3].map(i => (
            <div key={i} className="h-16 bg-gray-100 rounded animate-pulse" />
          ))}
        </div>
      ) : drafts.length === 0 ? (
        <div className="bg-white rounded-lg border border-gray-200 p-12 text-center">
          <p className="text-gray-500">No drafts waiting for review.</p>
          <p className="text-sm text-gray-400 mt-2">Generate a blog post from a knowledge asset in Generate Content, and it'll show up here.</p>
        </div>
      ) : (
        <div className="bg-white rounded-lg border border-gray-200 overflow-hidden">
          <table className="w-full">
            <thead className="bg-gray-50 border-b">
              <tr>
                <th className="text-left p-3 text-sm font-medium text-gray-500">Title</th>
                <th className="text-left p-3 text-sm font-medium text-gray-500">Category</th>
                <th className="text-left p-3 text-sm font-medium text-gray-500">Word Count</th>
                <th className="text-left p-3 text-sm font-medium text-gray-500">Status</th>
                <th className="text-left p-3 text-sm font-medium text-gray-500">Created</th>
                <th className="text-right p-3 text-sm font-medium text-gray-500">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-100">
              {drafts.map((draft) => (
                <tr key={draft.id} className="hover:bg-gray-50">
                  <td className="p-3 font-medium text-gray-900">{draft.title || '(untitled)'}</td>
                  <td className="p-3 text-sm text-gray-500">{draft.category || 'Uncategorized'}</td>
                  <td className="p-3 text-sm text-gray-500">{draft.word_count || '—'}</td>
                  <td className="p-3">
                    <span className="text-xs font-semibold bg-amber-100 text-amber-700 rounded-full px-2 py-0.5">
                      {draft.status || 'draft'}
                    </span>
                  </td>
                  <td className="p-3 text-sm text-gray-500">
                    {draft.created_at ? new Date(draft.created_at).toLocaleDateString() : '—'}
                  </td>
                  <td className="p-3 text-right">
                    <div className="flex justify-end gap-2">
                      <Link
                        href={`/admin/blog/${draft.id}/edit`}
                        className="text-blue-600 hover:text-blue-800 text-sm font-medium"
                      >
                        Edit
                      </Link>
                      <button
                        onClick={() => publishDraft(draft.id)}
                        className="text-green-600 hover:text-green-800 text-sm font-medium"
                      >
                        Publish
                      </button>
                      <button
                        onClick={() => deleteDraft(draft.id)}
                        className="text-red-600 hover:text-red-800 text-sm font-medium"
                      >
                        Delete
                      </button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
}