'use client';

import { useState, useEffect } from 'react';
import { createBrowserClient } from '@/lib/supabase';
import Link from 'next/link';

export default function BossBattleDraftsPage() {
  const [drafts, setDrafts] = useState([]);
  const [loading, setLoading] = useState(true);
  const [expandedId, setExpandedId] = useState(null);
  const [publishing, setPublishing] = useState(null);
  const supabase = createBrowserClient();

  useEffect(() => {
    loadDrafts();
  }, []);

  const loadDrafts = async () => {
    setLoading(true);
    const { data, error } = await supabase
      .from('boss_battle_drafts')
      .select('*, knowledge_assets(keyword)')
      .order('created_at', { ascending: false });
    if (error) console.error(error);
    setDrafts(data || []);
    setLoading(false);
  };

  const deleteDraft = async (id) => {
    if (!confirm('Delete this boss battle draft?')) return;
    const { error } = await supabase.from('boss_battle_drafts').delete().eq('id', id);
    if (error) alert(error.message);
    else loadDrafts();
  };

  const publishDraft = async (id) => {
    setPublishing(id);
    try {
      const res = await fetch(`/api/boss-battles/${id}/publish`, { method: 'POST' });
      const data = await res.json();
      if (!res.ok) {
        alert('Publish failed: ' + data.error);
      } else {
        alert(`✅ Published! ${data.questionCount} questions synced to past_questions.`);
        loadDrafts();
      }
    } catch (e) {
      alert('Publish failed: ' + e.message);
    }
    setPublishing(null);
  };

  const toggleExpand = (id) => setExpandedId(expandedId === id ? null : id);

  return (
    <div className="space-y-6">
      <section className="rounded-2xl bg-white p-6 shadow-sm border">
        <Link href="/admin/dashboard" className="text-sm text-brand-blue underline">← Back to Admin</Link>
        <div className="flex items-center justify-between mt-2">
          <div>
            <h1 className="text-2xl font-extrabold text-brand-blue">👹 Boss Battle Drafts</h1>
            <p className="text-sm text-gray-500">Bosses generated by the content engine land here. Review, then publish.</p>
          </div>
          <Link href="/admin/boss-battles" className="text-sm text-blue-600 hover:underline">
            Manual boss battles →
          </Link>
        </div>
      </section>

      {loading ? (
        <div className="text-center py-8">Loading...</div>
      ) : drafts.length === 0 ? (
        <div className="bg-white rounded-2xl border p-12 text-center text-gray-500">
          No boss battle drafts yet. Generate one from a knowledge asset in Generate Content.
        </div>
      ) : (
        <div className="grid gap-4">
          {drafts.map((draft) => (
            <div key={draft.id} className="bg-white rounded-2xl shadow-sm border p-4">
              <div className="flex items-start justify-between gap-4">
                <div className="flex-1">
                  <div className="flex items-center gap-2">
                    <p className="font-bold">{draft.name || draft.keyword}</p>
                    <span className={`text-xs font-semibold rounded-full px-2 py-0.5 ${
                      draft.status === 'published' ? 'bg-green-100 text-green-700' : 'bg-amber-100 text-amber-700'
                    }`}>
                      {draft.status}
                    </span>
                  </div>
                  <p className="text-sm text-gray-500">
                    {draft.subject} • Difficulty {draft.difficulty} • {(draft.questions || []).length} questions • +{draft.xp_reward} XP
                  </p>
                  {draft.knowledge_assets?.keyword && (
                    <p className="text-xs text-gray-400 mt-1">From: {draft.knowledge_assets.keyword}</p>
                  )}
                </div>
                <div className="flex gap-2 shrink-0">
                  <button onClick={() => toggleExpand(draft.id)} className="text-sm text-gray-600 hover:underline">
                    {expandedId === draft.id ? 'Hide' : 'Preview'}
                  </button>
                  <button
                    onClick={() => publishDraft(draft.id)}
                    disabled={publishing === draft.id}
                    className="bg-brand-yellow px-4 py-1.5 rounded-full text-sm font-bold hover:opacity-90 disabled:opacity-50"
                  >
                    {publishing === draft.id ? 'Publishing...' : draft.status === 'published' ? 'Republish' : 'Publish'}
                  </button>
                  <button onClick={() => deleteDraft(draft.id)} className="text-red-500 hover:underline text-sm">
                    Delete
                  </button>
                </div>
              </div>

              {expandedId === draft.id && (
                <div className="mt-4 border-t pt-4 space-y-3">
                  {(draft.questions || []).map((q, i) => (
                    <div key={i} className="text-sm bg-slate-50 rounded-xl p-3">
                      <p className="font-semibold">{i + 1}. {q.question}</p>
                      <ul className="mt-1 space-y-0.5 text-gray-600">
                        {(q.options || []).map((opt, oi) => (
                          <li key={oi} className={opt === q.correct_answer ? 'font-bold text-green-700' : ''}>
                            {String.fromCharCode(65 + oi)}. {opt}
                          </li>
                        ))}
                      </ul>
                    </div>
                  ))}
                </div>
              )}
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
